### ISSUE TITLE
Clarifications on the code

### ISSUE THREAD

**Issue by ZKC19940412** [sirmarcel/gknet-archive#1]
Dear developers of gknet:
Hi, thank you all so much for implementing such a powerful tool for MPNN and I believe it is definitely going to be super helpful for the community. I have been closely following the preprint and the code and have some clarification questions wanted to sort out:

In the infrastructure module, the fastcalculator implements the hardy formula and other form of heat fluxes, which is correct but inefficient and correspond to J_semilocal in the preprint correct?

In the infrastructure module, the [folded_calculator.py](https://github.com/sirmarcel/gknet-archive/blob/main/infrastructure/python/gknet/experimental/unfolded_heatflux/folded_calculator.py)  also uses very similar implementations as the unfoldedheatflux calculator, i.e. going through calculations of berry center and the force term. I would imagine this is a variation of the unfoldedheatflux implementation, which is faster than J_semilocal but slower than J_unfoldered and not been mentioned/discussed in the preprint correct?

Thank you so much for answering my questions, and have a nice day.

**Comment by sirmarcel** [comment]
Hi Zekun,

Thanks for your interest!

- `UnfoldedHeatFluxCalculator` implements the unfolded heat flux, which is the one shown in the paper. It's reasonably fast.
- `fastCalculator` is the calculator used for MD, and also implements various versions of the Hardy flux (slow)
- `FoldedCalculator` is some experiment that I forgot to delete 😆 I think it's the "unfolded" heat flux, but instead of the unfolded positions, it just uses the simulation cell positions -- which is wrong, so it gives wrong results, and which is why it's not mentioned in the paper. You should not use it!

**Comment by ZKC19940412** [comment]
Hi. Thank you so much for getting back to me. I am happy that I have just starting to learn from the Hardy flux (slow but right) first lol. One more question/clarification if you don't mind, in line 45 [unfolder.py](https://github.com/sirmarcel/gknet-archive/blob/main/infrastructure/python/gknet/experimental/unfolded_heatflux/unfolder.py), it says the cutoff should be smaller than half the smallest unit cell vector. Should I be just using that for the unfold operations? Say for a cubic silicon cell with lattice constants of 5.432A, the cutoff for the unfold operations is about 2.715A. Does it sound reasonable? Again, thank you so much for clarifying the code and my question. 

Best, 
Zekun

**Comment by sirmarcel** [comment]
Please feel very free to keep asking questions! I did not expect anyone to look at this code, it's a delight.

I think my comment in that file may in fact not be entirely accurate. There's a number of closely related issues with the cutoff:

- The minimum image convention (as typically implemented) only strictly applies if the cutoff is <= half the cell. While SchNetPack can handle larger cutoffs, I'm a bit sceptical and would avoid it.
- For the Hardy heat flux to be correct, the *effective* cutoff of the MPNN (i.e. M*rc) must be <= half the cell. This is because the m.i.c. is used for the R_IJ prefactors.
- For the unfolded heat flux to be correct, it is sufficient for the effective cutoff to be as large as the cell. (I think!) This is because the mic is not used.

In general, you would run heat flux calculations for larger supercells anyhow, for reasons of convergence. For training I would aim to make sure that the cutoff is <= half the cell size. (By cell size I mean the minimum distance between opposite faces of the simulation cell; in orhorhombic systems this is just the length of the smallest lattice vector.)

**Comment by ZKC19940412** [comment]
For sure. Thank you so much for the clarifications. Can you point out a little bit where in the code this M*rc condition is used for Hardy heat flux? The closet place I could image will be the "skin" parameter that is used in line 125 in [calculator.py](https://github.com/sirmarcel/gknet-archive/blob/main/infrastructure/python/gknet/experimental/fast_calculator/calculator.py) to handle the conversions between atom object and Schnet graph. Thank you so much for reassuring the cutoff for the unfolded heat flux. I am closet to understand how it is implemented and be ready to modify it when needed.  I will definitely ask more questions when I get to play around with it more.  Also thank you so much for fast respond, best luck with the presentation regrading this work tomorrow.  I am pretty sure a lot of people will be interested in it. 

Best, 
Zekun

**Comment by sirmarcel** [comment]
The cutoff is currently not checked... I should probably emit a warning. This is done in the new `jax` infrastructure, which is not yet public...

The `skin` parameter is just an additional tolerance to avoid re-computing neighborlists and the unfolding if atoms move only a little bit. If you check `unfolder_calculator.py` line 82, you see that M*rc gets passed into the unfolder.

Thanks -- we'll see who shows up tomorrow. :)

**Comment by ZKC19940412** [comment]
Hi Marcel. This is Zekun again. I have been on and off with understanding this unfolded heat flux. For what I understand, the unfolded heat flux transforms a pbc system into an unfolded (non-pbc) representation and convert that unfolded representation to a graph which pairs with a MPNN so that the virial and energy of the berry centers can be predicted and used to compute the heat flux. I was able to transform my system from a pbc one to an non-pbc with the codes in zipped files. However, I saw an atom objects with much more # of atoms. Is that what I would expect? If so, how do I map, say, the velocities from the pbc systems onto these non-pbc representation and set the cuff off for my MPNN? Sorry I didn't use schnet, but I would image there is a cutoff parameter for which you would use to decide up to certain angstrom , the predictions are somehow truncated or updated implicitly by message passing. I wonder if I should use the same cutoff parameter I have for the pbc system for this unfold representation. 

Thank u so much for answering my questions.

Best, 
Zekun

[unfold_transomration_Si.zip](https://github.com/sirmarcel/gknet-archive/files/11312961/unfold_transomration_Si.zip)

**Comment by sirmarcel** [comment]
Hi Zekun,

Great that you're still working on this. Let's see..

> For what I understand, the unfolded heat flux transforms a pbc system into an unfolded (non-pbc) representation and convert that unfolded representation to a graph which pairs with a MPNN so that the virial and energy of the berry centers can be predicted and used to compute the heat flux.

The `Unfolder` transforms a periodic system into a non-periodic systems where all the atoms within a distance of  `effective_cutoff` from the cell boundary have been explicitly replicated. If you then drop the resulting `Atoms` into the input conversion functions of whatever MPNN you're using (for example the `Converter` I use for SchNet), it should generate a graph for that "unfolded", no longer periodic system.

> I saw an atom objects with much more # of atoms. Is that what I would expect?

Yes, you should see more atoms. The (relative) amount of additional atoms will decrease with system size, but it's typically quite substantial.

> If so, how do I map, say, the velocities from the pbc systems onto these non-pbc representation ...

The `Unfolder` will automatically assign the same velocities to replicas. (If you look closely into the code, the `unfolding.idx` is an array that keeps track of the mapping between original atoms and replica atoms.)

> ... and set the cuff off for my MPNN? ... I wonder if I should use the same cutoff parameter I have for the pbc system for this unfold representation.

Yes, the cutoff in the your MPNN should be the *same* as before. The effective cutoff should be `number of interaction steps * cutoff`.

***

To recap: Let's say you have `N` atoms in your system. The `Unfolder` will give you a new `Atoms` object where the first `N` atoms are the original atoms (wrapped into the cell), and additionally `N_unf` atoms that are replicas, where the `Unfolder` has assigned the same masses, atomic numbers, and velocities as the original atoms. This system no longer has `pbc=True`: We have created it explicitly so that, from the perspective of the `N` atoms in the simulation cell,  it *looks* exactly like the infinite periodic system, but it actually is not -- it's just extended up to the maximum interaction range, i.e., how "far" the atoms in the cell can "see".

If you put this unfolded `Atoms` into a featuriser (the thing that makes the graph) and predict atomic energies for each atom, which I will call `Ui = [U_1, U_2, ...]`, then if you sum *over the first `N`* entries of `Ui`, you should get the *same* potential energy as you would get for the original periodic system. Is that is the case, everything has worked correctly and you can proceed!

I see in the code that you're trying to use this with MegNet, is that right? If you can point me to the implementation of MegNet you're using, I can take a quick look...

Hope this helps!

Cheers,

Marcel
